#!/usr/bin/env python3
"""Differential vectors for std.calendar against Python's datetime.

std.calendar converts between an epoch instant and a civil UTC date with two
kernels (`days_from_civil` and its inverse) and formats/parses two wire forms.
None of that touches the OS, so it can be checked exhaustively against an
authority that shares the same definitions: Python's `datetime` is proleptic
Gregorian, spans years 1..9999 exactly as std.calendar does, and has no leap
seconds — the same three decisions.

This script picks a deterministic, wide range of epoch seconds (negative ones
well before 1970, leap days, non-leap century years, both calendar ends), emits
a Beans program that converts and formats each one, and writes the output that
program must produce — every civil field, both wire forms, the civil->epoch
round-trip, and a parse round-trip of each form — computed here from datetime.
A single wrong day, weekday, or format byte makes the Beans output diverge from
this file and fails the test on both backends.

  python3 tools/calendar_vectors.py --count 5000 --seed 1 \
      --program out.b --expected out.txt
"""

import argparse
import random
from datetime import datetime, timedelta, timezone

EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)
# 0001-01-01T00:00:00Z and 9999-12-31T23:59:59Z, the range a DateTime holds.
MIN_EPOCH = int((datetime(1, 1, 1, tzinfo=timezone.utc) - EPOCH).total_seconds())
MAX_EPOCH = int(
    (datetime(9999, 12, 31, 23, 59, 59, tzinfo=timezone.utc) - EPOCH).total_seconds()
)

WEEKDAY_SHORT = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
MONTH_SHORT = [
    "", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
]


def is_leap(year):
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)


def civil_of(seconds):
    return EPOCH + timedelta(seconds=seconds)


def weekday_number(dt):
    # datetime.isoweekday(): Mon=1..Sun=7. std.calendar: Sun=0..Sat=6.
    return dt.isoweekday() % 7


def rfc3339(dt):
    return (
        f"{dt.year:04d}-{dt.month:02d}-{dt.day:02d}"
        f"T{dt.hour:02d}:{dt.minute:02d}:{dt.second:02d}Z"
    )


def http_date(dt):
    return (
        f"{WEEKDAY_SHORT[weekday_number(dt)]}, "
        f"{dt.day:02d} {MONTH_SHORT[dt.month]} {dt.year:04d} "
        f"{dt.hour:02d}:{dt.minute:02d}:{dt.second:02d} GMT"
    )


def day_of_year(dt):
    return dt.timetuple().tm_yday


def expected_line(seconds):
    dt = civil_of(seconds)
    leap = "true" if is_leap(dt.year) else "false"
    # The last three columns are Beans self-consistency: civil->epoch and each
    # parse round-trip must return the very second we started from.
    return "|".join(
        [
            str(seconds),
            rfc3339(dt),
            http_date(dt),
            str(seconds),
            str(day_of_year(dt)),
            str(weekday_number(dt)),
            leap,
            str(seconds),
            str(seconds),
        ]
    )


# Boundary instants worth pinning regardless of the random draw.
def fixed_seconds():
    def at(y, mo, d, h=0, mi=0, s=0):
        return int(
            (datetime(y, mo, d, h, mi, s, tzinfo=timezone.utc) - EPOCH).total_seconds()
        )

    return [
        MIN_EPOCH,                       # 0001-01-01
        MAX_EPOCH,                       # 9999-12-31 23:59:59
        0,                               # the epoch itself
        -1,                              # one second before the epoch
        at(1969, 12, 31, 23, 59, 59),    # last second of 1969 (negative)
        at(2000, 2, 29, 12, 0, 0),       # leap day of a leap century
        at(1900, 2, 28, 23, 59, 59),     # 1900 is not a leap year
        at(1900, 3, 1),                  # the day after
        at(2024, 2, 29),                 # ordinary leap day
        at(1582, 10, 15),                # Gregorian reform date (proleptic here)
        at(1, 12, 31, 23, 59, 59),       # deep negative, near year 1
        at(9999, 1, 1),                  # start of the last year
        at(1994, 11, 6, 8, 49, 37),      # RFC 9110's own example
    ]


BEANS_PROGRAM = '''// GENERATED by tools/calendar_vectors.py — do not edit by hand.
// Converts each epoch second to a civil UTC DateTime and prints every field
// the vector file checks against Python's datetime.
import std.io
import std.calendar

fn line(seconds: int) -> string {{
    let stamp: calendar.DateTime =
        calendar.DateTime.from_epoch_seconds(seconds).expect("in range")
    let rfc: string = stamp.to_rfc3339()
    let http: string = stamp.to_http_date()
    let back_rfc: calendar.DateTime =
        calendar.DateTime.parse_rfc3339(rfc).expect("its own rfc3339 parses")
    let back_http: calendar.DateTime =
        calendar.DateTime.parse_http_date(http).expect("its own http date parses")
    let leap: string =
        if calendar.is_leap_year(stamp.year) {{ "true" }} else {{ "false" }}
    return "{{seconds}}|{{rfc}}|{{http}}|{{stamp.epoch_seconds()}}|{{stamp.day_of_year()}}|{{stamp.weekday().number()}}|{{leap}}|{{back_rfc.epoch_seconds()}}|{{back_http.epoch_seconds()}}"
}}

fn main() {{
    let inputs: List<int> = [
{rows}
    ]
    for seconds: int in inputs {{
        io.println(line(seconds))
    }}
}}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=5000)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--program", required=True)
    parser.add_argument("--expected", required=True)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    seconds = list(fixed_seconds())
    for _ in range(max(0, args.count - len(seconds))):
        seconds.append(rng.randint(MIN_EPOCH, MAX_EPOCH))

    rows = ",\n".join(f"        {value}" for value in seconds)
    with open(args.program, "w") as handle:
        handle.write(BEANS_PROGRAM.format(rows=rows))

    with open(args.expected, "w") as handle:
        for value in seconds:
            handle.write(expected_line(value) + "\n")


if __name__ == "__main__":
    main()
