#!/usr/bin/env python3
"""Inventory of everything the native backend declares it cannot emit yet.

The emitter refuses unsupported constructs with a message ending in "yet".
Scattered through the source those refusals are invisible: nobody knows how
many there are, which ones the interpreter happily runs, or whether a release
added new ones. Most of them are the same shape as the class-to-interface
return upcast fixed in this tree — the checker accepts the program, `beansc
run` runs it and prints the right answer, and only `beansc build` refuses. A
program that runs but will not build is a bug, not a documented limit, and
each untriaged line here is a candidate.

This writes a stable TSV so the set can be diffed in review and held by a gate.
The `status` column is carried over from the existing file, so triage survives
a regeneration; a newly appeared gap starts as `unknown`.

Usage:
    tools/emitter_gaps.py                 # rewrite test/emitter_gaps.tsv
    tools/emitter_gaps.py --check         # fail if the file is out of date
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "test" / "emitter_gaps.tsv"
SOURCES = sorted(ROOT.glob("src/llvm*.b"))

STATUS_VALUES = {
    # the interpreter runs this; only `beansc build` refuses. Same shape as a
    # fixed bug — a program that runs but will not build.
    "interpreter-ok",
    # refused on both paths, so the language does not offer it either way
    "both-refuse",
    # unreachable in practice: an internal invariant, not a user-facing limit
    "internal",
    # not triaged yet
    "unknown",
}


def strings_in(line):
    """Every Beans string literal on one line, body only.

    A `{...}` interpolation may itself hold string literals — one message
    reads `does not support {if is_ok { "ok" } else { "err" }} payload` — so
    a quote only closes the string at brace depth zero. A plain regex reads
    that message as two, and gets both wrong.
    """
    out, index, length = [], 0, len(line)
    while index < length:
        char = line[index]
        if char == "/" and line[index + 1:index + 2] == "/":
            break
        if char != '"':
            index += 1
            continue
        index += 1
        start, depth = index, 0
        while index < length:
            char = line[index]
            if char == "\\":
                index += 2
                continue
            if char == "{":
                depth += 1
            elif char == "}":
                if depth > 0:
                    depth -= 1
            elif char == '"' and depth == 0:
                break
            index += 1
        if index >= length:
            # unterminated on this line: not a message we can read
            break
        out.append(line[start:index])
        index += 1
    return out


def blank_holes(text):
    """Replace every interpolation, nesting included, with a single X.

    The shape has to stay put when the type a message names changes, or the
    inventory would churn on every program compiled.
    """
    out, index, length = [], 0, len(text)
    while index < length:
        if text[index] != "{":
            out.append(text[index])
            index += 1
            continue
        depth, index = 0, index
        while index < length:
            if text[index] == "{":
                depth += 1
            elif text[index] == "}":
                depth -= 1
                if depth == 0:
                    index += 1
                    break
            index += 1
        out.append("X")
    return "".join(out)


def scan():
    """Every declared gap, as (file, line, shape)."""
    found = []
    for path in SOURCES:
        rel = path.relative_to(ROOT).as_posix()
        for number, raw in enumerate(path.read_text().splitlines(), 1):
            for body in strings_in(raw):
                if "yet" not in body:
                    continue
                shape = blank_holes(body).strip()
                # a message, not a stray word: every refusal names the emitter
                if not shape.startswith("LLVM emitter"):
                    continue
                found.append((rel, number, shape))
    return sorted(found)


def load_status():
    """Triage from the current file, keyed by message shape."""
    status = {}
    if not INVENTORY.exists():
        return status
    for line in INVENTORY.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 4 and parts[0] != "file":
            status[parts[2]] = parts[3]
    return status


def render(rows, status):
    out = [
        "# Gaps the native backend declares. Generated by tools/emitter_gaps.py;",
        "# run it after adding or removing an emitter refusal.",
        "#",
        "# status is triage, and is preserved across regeneration:",
        "#   interpreter-ok  the interpreter runs it, only `beansc build` refuses",
        "#                   — a program that runs but will not build, i.e. a bug",
        "#   both-refuse     neither path offers it, so it is a real language limit",
        "#   internal        an invariant, not something a user program can reach",
        "#   unknown         not triaged",
        "#",
        "file\tline\tmessage\tstatus",
    ]
    for path, number, shape in rows:
        out.append(f"{path}\t{number}\t{shape}\t{status.get(shape, 'unknown')}")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rows = scan()
    status = load_status()
    for shape, value in status.items():
        if value not in STATUS_VALUES:
            print(
                f"unknown status {value!r} for {shape!r}; "
                f"use one of {sorted(STATUS_VALUES)}",
                file=sys.stderr,
            )
            return 1
    text = render(rows, status)

    if args.check:
        current = INVENTORY.read_text() if INVENTORY.exists() else ""
        if current != text:
            print(
                "test/emitter_gaps.tsv is out of date; "
                "run tools/emitter_gaps.py",
                file=sys.stderr,
            )
            return 1
        shapes = {shape for _, _, shape in rows}
        untriaged = sum(
            1 for shape in shapes if status.get(shape, "unknown") == "unknown"
        )
        print(
            f"ok emitter gaps: {len(rows)} sites, {len(shapes)} shapes, "
            f"{untriaged} untriaged"
        )
        return 0

    INVENTORY.write_text(text)
    shapes = {shape for _, _, shape in rows}
    print(f"wrote {INVENTORY.relative_to(ROOT)}: {len(rows)} sites, {len(shapes)} shapes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
