#!/usr/bin/env python3
"""Generate test/cases/math_vectors.b — the reference vectors for std.math.

HOW THESE NUMBERS WERE PRODUCED, which is the part that matters.

At f32 a vector is a constant a reader can check by eye: `exp(1) is 2.7182817`
either looks right or it does not. At f64 nobody checks seventeen digits, so
whatever the vectors were derived FROM becomes the thing under test, and it is
the part nobody re-examines later. So: every expected value here is the host
platform's libm, reached through CPython's `math` module, captured as the raw
64-bit pattern rather than as printed digits. libm on the platforms Beans
supports is correctly rounded to well under an ulp for these three functions,
so a disagreement of more than the tolerance below is Beans being wrong, not
the reference.

The inputs are chosen to exercise the parts that break rather than the parts
that work: the ends of exp's finite range and its subnormal tail, angles far
enough out that argument reduction is what is being tested, angles small
enough that the polynomial is, and the quadrant boundaries where a reduction
that is off by one turn shows up as a sign error rather than a small error.

Regenerate with:  python3 tools/gen_math_vectors.py
The file it writes is committed; this script is the derivation, kept beside it.
"""
import math, struct

def bits(x):
    return struct.unpack('<Q', struct.pack('<d', x))[0]

rows = []

def add(fn_name, x):
    ref = {'exp': math.exp, 'sin': math.sin, 'cos': math.cos}[fn_name]
    try:
        y = ref(x)
    except OverflowError:
        return
    if math.isinf(y) or math.isnan(y):
        return
    rows.append((fn_name, x, y))

# exp: both ends of the finite range, the subnormal tail, and a sweep between
for n in range(-7450, 7101, 61):
    add('exp', n / 10.0)
for x in (0.0, 1.0, -1.0, 0.5, -0.5, 1e-8, -1e-8, 700.0, -700.0,
          709.0, -740.0, -745.0, 88.0, -88.0):
    add('exp', x)

# sin and cos: the quadrant boundaries first, where a reduction that is off by
# a turn shows up as a wrong sign rather than a small error
for q in range(-8, 9):
    for off in (-1e-9, 0.0, 1e-9):
        x = q * (math.pi / 2) + off
        add('sin', x)
        add('cos', x)

# small angles, where the polynomial is what is being tested
for n in range(1, 40):
    x = n * 1e-7
    add('sin', x)
    add('cos', x)

# a sweep over several periods, then far enough out that the reduction is
for n in range(-3000, 3001, 137):
    x = n / 97.0
    add('sin', x)
    add('cos', x)
for n in range(1, 60):
    x = n * 2617.0 + 0.37
    add('sin', x)
    add('cos', x)
for n in range(1, 20):
    x = n * 41000.0 + 0.125
    add('sin', x)
    add('cos', x)

lines = [
    "// GENERATED by tools/gen_math_vectors.py — do not edit by hand.",
    "//",
    "// Expected values are the host libm's, captured as raw 64-bit patterns",
    "// rather than printed digits. The generator's docstring records how they",
    "// were produced and why the inputs are these; at f64 the derivation is the",
    "// thing under test, because nobody checks seventeen digits by eye.",
    "package main",
    "",
    "import std.io",
    "import std.math",
    "import std.encoding.binary",
    "",
    "fn bits_of(value: float) -> u64 {",
    "    var buffer: Bytes = new Bytes(8)",
    "    match binary.write_f64(buffer, 0, value, binary.ByteOrder.little) {",
    "        ok(_) => {}",
    "        err(_) => {}",
    "    }",
    "    match binary.read_u64(buffer, 0, binary.ByteOrder.little) {",
    "        ok(word) => { return word }",
    "        err(_) => { return 0 }",
    "    }",
    "}",
    "",
    "fn from_bits(word: u64) -> float {",
    "    var buffer: Bytes = new Bytes(8)",
    "    match binary.write_u64(buffer, 0, word, binary.ByteOrder.little) {",
    "        ok(_) => {}",
    "        err(_) => {}",
    "    }",
    "    match binary.read_f64(buffer, 0, binary.ByteOrder.little) {",
    "        ok(value) => { return value }",
    "        err(_) => { return 0.0 }",
    "    }",
    "}",
    "",
    "// Distance in representable steps. The sign bit is folded so that values",
    "// either side of zero are one step apart rather than 2^63.",
    "fn ordered(word: u64) -> int {",
    "    let raw: int = word as int",
    "    if raw < 0 {",
    "        return -(raw & 0x7fffffffffffffff) ",
    "    }",
    "    return raw",
    "}",
    "",
    "fn ulp_gap(got: float, want: float) -> int {",
    "    if got == want {",
    "        return 0",
    "    }",
    "    let a: int = ordered(bits_of(got))",
    "    let b: int = ordered(bits_of(want))",
    "    if a > b {",
    "        return a - b",
    "    }",
    "    return b - a",
    "}",
    "",
    "fn main() {",
    "    var worst_exp: int = 0",
    "    var worst_sin: int = 0",
    "    var worst_cos: int = 0",
    "    var checked: int = 0",
]
for name, x, y in rows:
    lines.append(
        f"    checked = checked + 1")
    lines.append(
        f"    worst_{name} = biggest(worst_{name}, "
        f"ulp_gap(math.{name}(from_bits({bits(x)})), from_bits({bits(y)})))")
lines += [
    "    io.println(\"checked {checked}\")",
    "    io.println(\"exp {worst_exp}\")",
    "    io.println(\"sin {worst_sin}\")",
    "    io.println(\"cos {worst_cos}\")",
    "}",
    "",
    "fn biggest(left: int, right: int) -> int {",
    "    if left > right {",
    "        return left",
    "    }",
    "    return right",
    "}",
]
open('test/cases/math_vectors.b', 'w').write("\n".join(lines) + "\n")
print(f"{len(rows)} vectors")
